import { useState } from "react";
import QRCode from "qrcode";
import { jsPDF } from "jspdf";

export interface DownloadOptions {
  text: string;
  title?: string;
  foregroundColor?: string;
  backgroundColor?: string;
  size?: number;
  margin?: number;
  errorCorrectionLevel?: "L" | "M" | "Q" | "H";
}

export const useQRDownloader = () => {
  const [isDownloading, setIsDownloading] = useState(false);
  const [downloadError, setDownloadError] = useState<string | null>(null);

  const downloadQR = async (
    format: "png" | "svg" | "pdf",
    options: DownloadOptions
  ) => {
    const {
      text,
      title = "qrverse-code",
      foregroundColor = "#4F46E5",
      backgroundColor = "#FFFFFF",
      size = 512,
      margin = 4,
      errorCorrectionLevel = "H",
    } = options;

    setIsDownloading(true);
    setDownloadError(null);

    // Sanitize filename
    const safeTitle = title.trim().toLowerCase().replace(/[^a-z0-9_-]/g, "-") || "qr-code";
    const filename = `${safeTitle}-${format}`;

    try {
      if (format === "svg") {
        // Generate native SVG vector using the qrcode library
        const svgString = await QRCode.toString(text, {
          type: "svg",
          margin,
          width: size,
          color: {
            dark: foregroundColor,
            light: backgroundColor,
          },
          errorCorrectionLevel,
        });

        const blob = new Blob([svgString], { type: "image/svg+xml;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${filename}.svg`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(url);
      } else if (format === "png") {
        // Generate high-resolution PNG on-the-fly
        const dataUrl = await QRCode.toDataURL(text, {
          margin,
          width: size,
          color: {
            dark: foregroundColor,
            light: backgroundColor,
          },
          errorCorrectionLevel,
        });

        const link = document.createElement("a");
        link.href = dataUrl;
        link.download = `${filename}.png`;
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
      } else if (format === "pdf") {
        // Generate high-res image first to place inside PDF
        const dataUrl = await QRCode.toDataURL(text, {
          margin,
          width: 1024, // Use large scale for high resolution print in PDF
          color: {
            dark: foregroundColor,
            light: backgroundColor,
          },
          errorCorrectionLevel,
        });

        // Create PDF (Single-page document with centered QR code and elegant template layout)
        const pdf = new jsPDF({
          orientation: "portrait",
          unit: "mm",
          format: "a4",
        });

        // Add elegant heading
        pdf.setFont("helvetica", "bold");
        pdf.setFontSize(22);
        pdf.setTextColor(15, 23, 42); // slate-900
        pdf.text("QRVERSE SECURE SYSTEM", 105, 40, { align: "center" });

        pdf.setFont("helvetica", "normal");
        pdf.setFontSize(10);
        pdf.setTextColor(100, 116, 139); // slate-500
        pdf.text("Enterprise-Grade Secure Scan Routing", 105, 46, { align: "center" });

        // Add QR code image centered
        // A4 size: 210mm x 297mm. Centering a 120mm x 120mm QR code
        const qrSize = 120;
        const xPos = (210 - qrSize) / 2;
        const yPos = 65;
        pdf.addImage(dataUrl, "PNG", xPos, yPos, qrSize, qrSize);

        // Add details panel below
        pdf.setDrawColor(226, 232, 240); // slate-200
        pdf.setLineWidth(0.5);
        pdf.line(40, 200, 170, 200);

        pdf.setFontSize(9);
        pdf.setFont("helvetica", "bold");
        pdf.setTextColor(71, 85, 105); // slate-600
        pdf.text("SCAN INFORMATION", 40, 210);

        pdf.setFont("helvetica", "normal");
        pdf.setTextColor(100, 116, 139);
        pdf.text(`Title: ${title}`, 40, 218);
        
        // Wrap URL text to fit nicely on the document
        const maxUrlLength = 65;
        const displayUrl = text.length > maxUrlLength ? text.substring(0, maxUrlLength) + "..." : text;
        pdf.text(`Target URL: ${displayUrl}`, 40, 224);
        pdf.text(`Secure Routing Check: Verified HTTPS`, 40, 230);

        // Footer note
        pdf.setFontSize(8);
        pdf.setFont("helvetica", "italic");
        pdf.setTextColor(148, 163, 184); // slate-400
        pdf.text("This QR code was securely generated by QRVerse. All data streams are encrypted and protected.", 105, 260, { align: "center" });

        pdf.save(`${filename}.pdf`);
      }
    } catch (err: any) {
      console.error("QR Code export failure:", err);
      setDownloadError(err.message || "Failed to download QR code in the requested format.");
    } finally {
      setIsDownloading(false);
    }
  };

  return {
    downloadQR,
    isDownloading,
    downloadError,
  };
};
